version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: odontogram-api-postgres
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: test-database
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
# volumes:
#   postgres_data:
